[connections.snowflake]
account = "FSZCAWN-FVB22725"
user = "DWW"
password = "ziwxon-soCzev-5jisju"
role = "SYSADMIN"
warehouse = "COMPUTE_WH"
database = "SMOOTHIES"
schema = "PUBLIC"
client_session_keep_active = true